### ISSUE TITLE
Circuitscape.org references need to be updated to linkagemapper.org

### ISSUE THREAD

**Issue by dkav** [linkagescape/linkagemapper.org#2]
See https://github.com/linkagescape/linkagemapper.org/search?q=circuitscape.org

**Comment by aman-275** [comment]
updated the circuitscape.org reference where it was pointing to circuitscape.org/linkagemapper to linkagemapper . kindly let me if i miss out something .

**Comment by dkav** [comment]
I think you got them. 

By the way, the correct url for the Circuitscape website is https://circuitscape.org/. The http://www.circuitscape.org/ url redirects but the non-secure http protocol can be flagged, at least on the first access.

**Comment by dkav** [comment]
Fixed in https://github.com/linkagescape/linkagemapper.org/commit/956a423b860296c66338a13bf798704b028ffde2 and https://github.com/linkagescape/linkagemapper.org/commit/27144766e587c1453640c1a2b8737c22d21e84c1.
